services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    restart: unless-stopped

  web:
    build: web/
    ports:
      - "7777:80"
    depends_on:
      - api
    restart: unless-stopped
